### ISSUE TITLE
Create hackerrank file then add any coding problem solutions

### ISSUE THREAD

**Issue by MryashAditya007** [MryashAditya007/Hacktoberfest2023#1]

**Comment by yashwantaditya009** [comment]
I can solve this problem please assign me.

**Comment by codedmachine111** [comment]
If this issue is not assigned to anyone, could you please assign it to me? I would love to add a new folder to the repository named "hackerrank" and add solutions to a few problems in **Java**. Thankyou.

**Comment by MryashAditya007** [comment]
> If this issue is not assigned to anyone, could you please assign it to me? I would love to add a new folder inside "hackerrank" and add solutions to a few problems in **Java** programming language. Thankyou.

@codedmachine111  Sure, you can add Java programming solutions

**Comment by codedmachine111** [comment]
Thanks for assigning the task. Will be adding a few problems of all difficulty levels (Easy, Medium and Hard) in Java.

**Comment by Mohitt0** [comment]
hey @MryashAditya007 assign me

**Comment by goswamiprad** [comment]
If it is still open for contributions, assign it to me then. @MryashAditya007

**Comment by MauryaD** [comment]
Hi @MryashAditya007,
Could you please assign this issue to me. Here's my Hackerrank profile please.
https://www.hackerrank.com/deepakmaurya2198

Although, these days, I'm doing Leetcode, if you want I can work on Leetcode problems as well.

Thanks!!
