### ISSUE TITLE
Add N-Queens problem solution

### ISSUE THREAD

**Issue by blindaks** [MryashAditya007/Hacktoberfest2023#105]
I want to add N-Queens Problem solution in LeetCode, using backtracking approach.

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign me this issue.

**Comment by aniket-singh-01** [comment]
hey i solved it. can you please check it and do the process. 
It's my first ever open source contribution

**Comment by mehakbasrani** [comment]
I want to contribute to this. Please assign it to me.

**Comment by aryangandhi05** [comment]
I would like to contribute. Please assign this question to me
