### ISSUE TITLE
Rock-paper-scissor game :)

### ISSUE THREAD

**Issue by competitiveblood** [MryashAditya007/Hacktoberfest2023#123]
Rock-paper-scissors is a hand-based game between two players, in which each player simultaneously forms one of three shapes with an outstretched hand. These shapes are "rock" (a closed fist), "paper" (a flat hand), and "scissors" (a fist with the index and middle fingers extended).

The game has only three possible outcomes:

Rock beats scissors (rock crushes scissors)
Scissors beats paper (scissors cuts paper)
Paper beats rock (paper covers rock)
If both players choose the same shape, the game is a tie.

The game is often played as a best-of-three series, but it can also be played as a single round.

Rock-paper-scissors is a simple game, but it is also a lot of fun. It is a great game to play with friends and family, and it can be enjoyed by people of all ages.

Sources
en.wikipedia.org/wiki/Rock_paper_scissors
apkpure.com/rps-rock-paper-scissors/com.kixes.rps

profile picture
make the intro of the game such that I making that game in python language 

View other drafts

Sure, here is a more intro of the game explaining how I'm making it in Python:

I'm making a rock-paper-scissors game in Python. This is a classic two-player game where each player chooses one of three shapes: rock, paper, or scissors. The winner is determined by the following rules:

Rock beats scissors
Scissors beats paper
Paper beats rock
If both players choose the same shape, the game is a tie.

I'm using Python to make this game because it is a popular and versatile language. It is also relatively easy to learn, making it a good choice for beginners.

To make the game, I'll start by importing the random module. This module allows us to generate random numbers, which we'll need to use to determine the computer's choice.

Next, I'll create a function to generate a random choice for the computer. This function will simply return one of the three shapes at random.

Then, I'll create a function to get the player's choice. This function will prompt the player to enter their choice and then return it.

Finally, I'll create a function to determine the winner of the game. This function will take the player's choice and the computer's choice as input and then return the winner.

Once I have all of these functions written, I can put them together to make the game. The game loop will simply prompt the player to enter their choice, generate the computer's choice, and then determine the winner. The game will continue until one player wins three rounds.

Your review and insights are vital as we enhance the repository's utility.

Happy coding :)

**Comment by Animesh2k3** [comment]
Please assign this to me

**Comment by nrhitik** [comment]
I would like to work on this issue. Could you please assign me this issue.

**Comment by nrhitik** [comment]
Could you please close this issue since the pullrequest for this issue has already been merged. or if there is anything regarding this issue that we need to look into, please let me know .

**Comment by competitiveblood** [comment]
I have already put pull request for the same last week but it didn't get accepted 
Wanted it to get merged :)

**Comment by competitiveblood** [comment]
I would to like to contribute in this issue
Please assign me this issue :)
