### ISSUE TITLE
Resolve NullPointerException in calculateTotalPrice Function (Java)

### ISSUE THREAD

**Issue by MryashAditya007** [MryashAditya007/Hacktoberfest2023#73]
Path - Problems/ShoppingCart.java

***Issue Description:***
The calculateTotalPrice function in the ShoppingCart.java file is throwing a NullPointerException when an item in the shopping cart has a null price. This issue needs to be resolved to ensure the correct calculation of the total price.

***Steps to Reproduce:***

Execute the calculateTotalPrice function in Java with a shopping cart containing an item with a null price.
Expected Behavior:
The function should handle items with null prices gracefully and calculate the total price correctly.

***Actual Behavior:***
The function throws a NullPointerException when encountering an item with a null price, causing the calculation to fail.

***Proposed Solution:***
To resolve this issue, we need to modify the calculateTotalPrice function in the ShoppingCart.java file to check for null prices before adding them to the total. If an item has a null price, it should be skipped in the calculation.
This modification ensures that items with null prices are excluded from the calculation, preventing the NullPointerException.

***Additional Information:***

Relevant code file: ShoppingCart.java
Environment: Java 8, ShoppingCart version 1.2.3
Labels: bug, NullPointerException

**Comment by AminAK11** [comment]
I dont get it. In Problems/ShoppingCart.java there is a class called public class DebugExample. There is no calculateTotalPrice or anything.  It just calls text.length where text = null and prints the result. What is the purpose of this issue? This is the first time i'm trying to contribute to an open source project.
